/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Address = IDL.Record({
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'fullName' : IDL.Text,
  'state' : IDL.Text,
  'phone' : IDL.Text,
});
export const ProductId = IDL.Nat;
export const Timestamp = IDL.Int;
export const DiscountType = IDL.Variant({
  'Percent' : IDL.Null,
  'Fixed' : IDL.Null,
});
export const CategoryId = IDL.Nat;
export const CreateCouponInput = IDL.Record({
  'discountValue' : IDL.Float64,
  'validFrom' : Timestamp,
  'code' : IDL.Text,
  'discountType' : DiscountType,
  'validTo' : Timestamp,
  'usageLimit' : IDL.Opt(IDL.Nat),
  'applicableCategories' : IDL.Vec(CategoryId),
  'minOrderAmount' : IDL.Opt(IDL.Float64),
});
export const CouponId = IDL.Nat;
export const Coupon = IDL.Record({
  'id' : CouponId,
  'discountValue' : IDL.Float64,
  'validFrom' : Timestamp,
  'code' : IDL.Text,
  'createdAt' : Timestamp,
  'discountType' : DiscountType,
  'usageCount' : IDL.Nat,
  'validTo' : Timestamp,
  'isActive' : IDL.Bool,
  'usageLimit' : IDL.Opt(IDL.Nat),
  'applicableCategories' : IDL.Vec(CategoryId),
  'minOrderAmount' : IDL.Opt(IDL.Float64),
});
export const CreateProductInput = IDL.Record({
  'sku' : IDL.Text,
  'categoryId' : CategoryId,
  'title' : IDL.Text,
  'reorderPoint' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'stock' : IDL.Nat,
  'compareAtPrice' : IDL.Opt(IDL.Float64),
  'subcategoryId' : IDL.Opt(CategoryId),
  'price' : IDL.Float64,
  'images' : IDL.Vec(IDL.Text),
});
export const Product = IDL.Record({
  'id' : ProductId,
  'sku' : IDL.Text,
  'categoryId' : CategoryId,
  'title' : IDL.Text,
  'reorderPoint' : IDL.Nat,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'updatedAt' : Timestamp,
  'stock' : IDL.Nat,
  'compareAtPrice' : IDL.Opt(IDL.Float64),
  'subcategoryId' : IDL.Opt(CategoryId),
  'price' : IDL.Float64,
  'soldCount' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const UserId = IDL.Principal;
export const DashboardStats = IDL.Record({
  'totalProducts' : IDL.Nat,
  'totalOrders' : IDL.Nat,
  'pendingOrders' : IDL.Nat,
  'lowStockCount' : IDL.Nat,
  'revenueToday' : IDL.Float64,
  'ordersToday' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalRevenue' : IDL.Float64,
});
export const LowStockAlert = IDL.Record({
  'title' : IDL.Text,
  'reorderPoint' : IDL.Nat,
  'productId' : ProductId,
  'stock' : IDL.Nat,
});
export const ReviewId = IDL.Nat;
export const ReviewStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Review = IDL.Record({
  'id' : ReviewId,
  'status' : ReviewStatus,
  'title' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'comment' : IDL.Text,
  'updatedAt' : Timestamp,
  'rating' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const AnalyticsPeriod = IDL.Variant({
  'Day' : IDL.Null,
  'Week' : IDL.Null,
  'Year' : IDL.Null,
  'Month' : IDL.Null,
});
export const RevenueByPeriod = IDL.Record({
  'revenue' : IDL.Float64,
  'period' : IDL.Text,
  'orderCount' : IDL.Nat,
});
export const TopProduct = IDL.Record({
  'title' : IDL.Text,
  'revenue' : IDL.Float64,
  'productId' : ProductId,
  'soldCount' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'Refunded' : IDL.Null,
  'Delivered' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Processing' : IDL.Null,
  'Shipped' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'PayPal' : IDL.Null,
  'Stripe' : IDL.Null,
  'MtnMomo' : IDL.Null,
});
export const OrderFilter = IDL.Record({
  'status' : IDL.Opt(OrderStatus),
  'paymentMethod' : IDL.Opt(PaymentMethod),
  'toDate' : IDL.Opt(Timestamp),
  'fromDate' : IDL.Opt(Timestamp),
  'customerId' : IDL.Opt(UserId),
});
export const OrderId = IDL.Nat;
export const OrderItem = IDL.Record({
  'title' : IDL.Text,
  'productId' : ProductId,
  'imageUrl' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'couponCode' : IDL.Opt(IDL.Text),
  'trackingNumber' : IDL.Opt(IDL.Text),
  'total' : IDL.Float64,
  'paymentMethod' : PaymentMethod,
  'discountAmount' : IDL.Float64,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'notes' : IDL.Opt(IDL.Text),
  'shippingAddress' : Address,
  'customerId' : UserId,
  'paymentReference' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(OrderItem),
  'subtotal' : IDL.Float64,
});
export const Role = IDL.Variant({ 'Customer' : IDL.Null, 'Admin' : IDL.Null });
export const UserPreferences = IDL.Record({
  'emailNotifications' : IDL.Bool,
  'language' : IDL.Text,
  'currency' : IDL.Text,
});
export const User = IDL.Record({
  'id' : UserId,
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
  'defaultAddressIndex' : IDL.Opt(IDL.Nat),
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'preferences' : UserPreferences,
  'updatedAt' : Timestamp,
  'addresses' : IDL.Vec(Address),
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const UpdateProductInput = IDL.Record({
  'sku' : IDL.Opt(IDL.Text),
  'categoryId' : IDL.Opt(CategoryId),
  'title' : IDL.Opt(IDL.Text),
  'reorderPoint' : IDL.Opt(IDL.Nat),
  'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
  'description' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Opt(IDL.Bool),
  'stock' : IDL.Opt(IDL.Nat),
  'compareAtPrice' : IDL.Opt(IDL.Float64),
  'subcategoryId' : IDL.Opt(CategoryId),
  'price' : IDL.Opt(IDL.Float64),
  'images' : IDL.Opt(IDL.Vec(IDL.Text)),
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'addedAt' : Timestamp,
  'quantity' : IDL.Nat,
});
export const ProductRatingSummary = IDL.Record({
  'ratingCounts' : IDL.Vec(IDL.Nat),
  'productId' : ProductId,
  'averageRating' : IDL.Float64,
  'totalReviews' : IDL.Nat,
});
export const Subcategory = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'slug' : IDL.Text,
});
export const Category = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'subcategories' : IDL.Vec(Subcategory),
});
export const ProductFilter = IDL.Record({
  'categoryId' : IDL.Opt(CategoryId),
  'inStockOnly' : IDL.Bool,
  'tags' : IDL.Vec(IDL.Text),
  'isActive' : IDL.Opt(IDL.Bool),
  'maxPrice' : IDL.Opt(IDL.Float64),
  'searchTerm' : IDL.Opt(IDL.Text),
  'subcategoryId' : IDL.Opt(CategoryId),
  'minPrice' : IDL.Opt(IDL.Float64),
});
export const CreateOrderInput = IDL.Record({
  'couponCode' : IDL.Opt(IDL.Text),
  'paymentMethod' : PaymentMethod,
  'shippingAddress' : Address,
  'items' : IDL.Vec(
    IDL.Record({ 'productId' : ProductId, 'quantity' : IDL.Nat })
  ),
});
export const RegisterInput = IDL.Record({
  'displayName' : IDL.Text,
  'email' : IDL.Text,
});
export const CreateReviewInput = IDL.Record({
  'title' : IDL.Text,
  'productId' : ProductId,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const UpdateProfileInput = IDL.Record({
  'displayName' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'preferences' : IDL.Opt(UserPreferences),
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const CouponValidation = IDL.Record({
  'discountAmount' : IDL.Float64,
  'message' : IDL.Text,
  'isValid' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addAddress' : IDL.Func([Address], [IDL.Bool], []),
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [IDL.Bool], []),
  'addToWishlist' : IDL.Func([ProductId], [IDL.Bool], []),
  'adminAdjustStock' : IDL.Func([ProductId, IDL.Int], [IDL.Bool], []),
  'adminBulkSetActive' : IDL.Func(
      [IDL.Vec(ProductId), IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'adminCreateCoupon' : IDL.Func([CreateCouponInput], [Coupon], []),
  'adminCreateProduct' : IDL.Func([CreateProductInput], [Product], []),
  'adminDeactivateCoupon' : IDL.Func([CouponId], [IDL.Bool], []),
  'adminDeactivateUser' : IDL.Func([UserId], [IDL.Bool], []),
  'adminDeleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'adminGetDashboardStats' : IDL.Func([], [DashboardStats], []),
  'adminGetLowStockAlerts' : IDL.Func([], [IDL.Vec(LowStockAlert)], []),
  'adminGetPendingReviews' : IDL.Func([], [IDL.Vec(Review)], []),
  'adminGetRevenueByPeriod' : IDL.Func(
      [AnalyticsPeriod, IDL.Nat],
      [IDL.Vec(RevenueByPeriod)],
      [],
    ),
  'adminGetTopProducts' : IDL.Func([IDL.Nat], [IDL.Vec(TopProduct)], []),
  'adminListCoupons' : IDL.Func([IDL.Bool], [IDL.Vec(Coupon)], []),
  'adminListOrders' : IDL.Func(
      [OrderFilter, IDL.Nat, IDL.Nat],
      [IDL.Vec(Order)],
      [],
    ),
  'adminListUsers' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(User)], []),
  'adminModerateReview' : IDL.Func([ReviewId, ReviewStatus], [IDL.Bool], []),
  'adminSetTrackingNumber' : IDL.Func([OrderId, IDL.Text], [IDL.Bool], []),
  'adminSetUserRole' : IDL.Func([UserId, Role], [IDL.Bool], []),
  'adminUpdateCoupon' : IDL.Func(
      [CouponId, CreateCouponInput],
      [IDL.Opt(Coupon)],
      [],
    ),
  'adminUpdateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
  'adminUpdateProduct' : IDL.Func(
      [ProductId, UpdateProductInput],
      [IDL.Opt(Product)],
      [],
    ),
  'cancelOrder' : IDL.Func([OrderId], [IDL.Bool], []),
  'clearCart' : IDL.Func([], [IDL.Bool], []),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getMyOrders' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Order)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getMyReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getOrderDetail' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductRating' : IDL.Func([ProductId], [ProductRatingSummary], ['query']),
  'getProductRatingSummary' : IDL.Func(
      [ProductId],
      [IDL.Opt(ProductId)],
      ['query'],
    ),
  'getProductReviews' : IDL.Func(
      [ProductId, IDL.Bool],
      [IDL.Vec(Review)],
      ['query'],
    ),
  'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'listProducts' : IDL.Func(
      [ProductFilter, IDL.Nat, IDL.Nat],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'placeOrder' : IDL.Func([CreateOrderInput], [Order], []),
  'registerUser' : IDL.Func([RegisterInput], [User], []),
  'removeAddress' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'removeFromCart' : IDL.Func([ProductId], [IDL.Bool], []),
  'removeFromWishlist' : IDL.Func([ProductId], [IDL.Bool], []),
  'searchProducts' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'seedData' : IDL.Func([], [IDL.Text], []),
  'setDefaultAddress' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'submitReview' : IDL.Func([CreateReviewInput], [Review], []),
  'updateCartItem' : IDL.Func([ProductId, IDL.Nat], [IDL.Bool], []),
  'updateMyProfile' : IDL.Func([UpdateProfileInput], [User], []),
  'validateCoupon' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Vec(CategoryId)],
      [CouponValidation],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Address = IDL.Record({
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'fullName' : IDL.Text,
    'state' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ProductId = IDL.Nat;
  const Timestamp = IDL.Int;
  const DiscountType = IDL.Variant({
    'Percent' : IDL.Null,
    'Fixed' : IDL.Null,
  });
  const CategoryId = IDL.Nat;
  const CreateCouponInput = IDL.Record({
    'discountValue' : IDL.Float64,
    'validFrom' : Timestamp,
    'code' : IDL.Text,
    'discountType' : DiscountType,
    'validTo' : Timestamp,
    'usageLimit' : IDL.Opt(IDL.Nat),
    'applicableCategories' : IDL.Vec(CategoryId),
    'minOrderAmount' : IDL.Opt(IDL.Float64),
  });
  const CouponId = IDL.Nat;
  const Coupon = IDL.Record({
    'id' : CouponId,
    'discountValue' : IDL.Float64,
    'validFrom' : Timestamp,
    'code' : IDL.Text,
    'createdAt' : Timestamp,
    'discountType' : DiscountType,
    'usageCount' : IDL.Nat,
    'validTo' : Timestamp,
    'isActive' : IDL.Bool,
    'usageLimit' : IDL.Opt(IDL.Nat),
    'applicableCategories' : IDL.Vec(CategoryId),
    'minOrderAmount' : IDL.Opt(IDL.Float64),
  });
  const CreateProductInput = IDL.Record({
    'sku' : IDL.Text,
    'categoryId' : CategoryId,
    'title' : IDL.Text,
    'reorderPoint' : IDL.Nat,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'stock' : IDL.Nat,
    'compareAtPrice' : IDL.Opt(IDL.Float64),
    'subcategoryId' : IDL.Opt(CategoryId),
    'price' : IDL.Float64,
    'images' : IDL.Vec(IDL.Text),
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'sku' : IDL.Text,
    'categoryId' : CategoryId,
    'title' : IDL.Text,
    'reorderPoint' : IDL.Nat,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'updatedAt' : Timestamp,
    'stock' : IDL.Nat,
    'compareAtPrice' : IDL.Opt(IDL.Float64),
    'subcategoryId' : IDL.Opt(CategoryId),
    'price' : IDL.Float64,
    'soldCount' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const UserId = IDL.Principal;
  const DashboardStats = IDL.Record({
    'totalProducts' : IDL.Nat,
    'totalOrders' : IDL.Nat,
    'pendingOrders' : IDL.Nat,
    'lowStockCount' : IDL.Nat,
    'revenueToday' : IDL.Float64,
    'ordersToday' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalRevenue' : IDL.Float64,
  });
  const LowStockAlert = IDL.Record({
    'title' : IDL.Text,
    'reorderPoint' : IDL.Nat,
    'productId' : ProductId,
    'stock' : IDL.Nat,
  });
  const ReviewId = IDL.Nat;
  const ReviewStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Review = IDL.Record({
    'id' : ReviewId,
    'status' : ReviewStatus,
    'title' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'productId' : ProductId,
    'comment' : IDL.Text,
    'updatedAt' : Timestamp,
    'rating' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const AnalyticsPeriod = IDL.Variant({
    'Day' : IDL.Null,
    'Week' : IDL.Null,
    'Year' : IDL.Null,
    'Month' : IDL.Null,
  });
  const RevenueByPeriod = IDL.Record({
    'revenue' : IDL.Float64,
    'period' : IDL.Text,
    'orderCount' : IDL.Nat,
  });
  const TopProduct = IDL.Record({
    'title' : IDL.Text,
    'revenue' : IDL.Float64,
    'productId' : ProductId,
    'soldCount' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'Refunded' : IDL.Null,
    'Delivered' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Processing' : IDL.Null,
    'Shipped' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'PayPal' : IDL.Null,
    'Stripe' : IDL.Null,
    'MtnMomo' : IDL.Null,
  });
  const OrderFilter = IDL.Record({
    'status' : IDL.Opt(OrderStatus),
    'paymentMethod' : IDL.Opt(PaymentMethod),
    'toDate' : IDL.Opt(Timestamp),
    'fromDate' : IDL.Opt(Timestamp),
    'customerId' : IDL.Opt(UserId),
  });
  const OrderId = IDL.Nat;
  const OrderItem = IDL.Record({
    'title' : IDL.Text,
    'productId' : ProductId,
    'imageUrl' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'couponCode' : IDL.Opt(IDL.Text),
    'trackingNumber' : IDL.Opt(IDL.Text),
    'total' : IDL.Float64,
    'paymentMethod' : PaymentMethod,
    'discountAmount' : IDL.Float64,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'notes' : IDL.Opt(IDL.Text),
    'shippingAddress' : Address,
    'customerId' : UserId,
    'paymentReference' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(OrderItem),
    'subtotal' : IDL.Float64,
  });
  const Role = IDL.Variant({ 'Customer' : IDL.Null, 'Admin' : IDL.Null });
  const UserPreferences = IDL.Record({
    'emailNotifications' : IDL.Bool,
    'language' : IDL.Text,
    'currency' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : UserId,
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
    'defaultAddressIndex' : IDL.Opt(IDL.Nat),
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'preferences' : UserPreferences,
    'updatedAt' : Timestamp,
    'addresses' : IDL.Vec(Address),
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const UpdateProductInput = IDL.Record({
    'sku' : IDL.Opt(IDL.Text),
    'categoryId' : IDL.Opt(CategoryId),
    'title' : IDL.Opt(IDL.Text),
    'reorderPoint' : IDL.Opt(IDL.Nat),
    'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
    'description' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Opt(IDL.Bool),
    'stock' : IDL.Opt(IDL.Nat),
    'compareAtPrice' : IDL.Opt(IDL.Float64),
    'subcategoryId' : IDL.Opt(CategoryId),
    'price' : IDL.Opt(IDL.Float64),
    'images' : IDL.Opt(IDL.Vec(IDL.Text)),
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'addedAt' : Timestamp,
    'quantity' : IDL.Nat,
  });
  const ProductRatingSummary = IDL.Record({
    'ratingCounts' : IDL.Vec(IDL.Nat),
    'productId' : ProductId,
    'averageRating' : IDL.Float64,
    'totalReviews' : IDL.Nat,
  });
  const Subcategory = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'slug' : IDL.Text,
  });
  const Category = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'subcategories' : IDL.Vec(Subcategory),
  });
  const ProductFilter = IDL.Record({
    'categoryId' : IDL.Opt(CategoryId),
    'inStockOnly' : IDL.Bool,
    'tags' : IDL.Vec(IDL.Text),
    'isActive' : IDL.Opt(IDL.Bool),
    'maxPrice' : IDL.Opt(IDL.Float64),
    'searchTerm' : IDL.Opt(IDL.Text),
    'subcategoryId' : IDL.Opt(CategoryId),
    'minPrice' : IDL.Opt(IDL.Float64),
  });
  const CreateOrderInput = IDL.Record({
    'couponCode' : IDL.Opt(IDL.Text),
    'paymentMethod' : PaymentMethod,
    'shippingAddress' : Address,
    'items' : IDL.Vec(
      IDL.Record({ 'productId' : ProductId, 'quantity' : IDL.Nat })
    ),
  });
  const RegisterInput = IDL.Record({
    'displayName' : IDL.Text,
    'email' : IDL.Text,
  });
  const CreateReviewInput = IDL.Record({
    'title' : IDL.Text,
    'productId' : ProductId,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const UpdateProfileInput = IDL.Record({
    'displayName' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'preferences' : IDL.Opt(UserPreferences),
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const CouponValidation = IDL.Record({
    'discountAmount' : IDL.Float64,
    'message' : IDL.Text,
    'isValid' : IDL.Bool,
  });
  
  return IDL.Service({
    'addAddress' : IDL.Func([Address], [IDL.Bool], []),
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [IDL.Bool], []),
    'addToWishlist' : IDL.Func([ProductId], [IDL.Bool], []),
    'adminAdjustStock' : IDL.Func([ProductId, IDL.Int], [IDL.Bool], []),
    'adminBulkSetActive' : IDL.Func(
        [IDL.Vec(ProductId), IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'adminCreateCoupon' : IDL.Func([CreateCouponInput], [Coupon], []),
    'adminCreateProduct' : IDL.Func([CreateProductInput], [Product], []),
    'adminDeactivateCoupon' : IDL.Func([CouponId], [IDL.Bool], []),
    'adminDeactivateUser' : IDL.Func([UserId], [IDL.Bool], []),
    'adminDeleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'adminGetDashboardStats' : IDL.Func([], [DashboardStats], []),
    'adminGetLowStockAlerts' : IDL.Func([], [IDL.Vec(LowStockAlert)], []),
    'adminGetPendingReviews' : IDL.Func([], [IDL.Vec(Review)], []),
    'adminGetRevenueByPeriod' : IDL.Func(
        [AnalyticsPeriod, IDL.Nat],
        [IDL.Vec(RevenueByPeriod)],
        [],
      ),
    'adminGetTopProducts' : IDL.Func([IDL.Nat], [IDL.Vec(TopProduct)], []),
    'adminListCoupons' : IDL.Func([IDL.Bool], [IDL.Vec(Coupon)], []),
    'adminListOrders' : IDL.Func(
        [OrderFilter, IDL.Nat, IDL.Nat],
        [IDL.Vec(Order)],
        [],
      ),
    'adminListUsers' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(User)], []),
    'adminModerateReview' : IDL.Func([ReviewId, ReviewStatus], [IDL.Bool], []),
    'adminSetTrackingNumber' : IDL.Func([OrderId, IDL.Text], [IDL.Bool], []),
    'adminSetUserRole' : IDL.Func([UserId, Role], [IDL.Bool], []),
    'adminUpdateCoupon' : IDL.Func(
        [CouponId, CreateCouponInput],
        [IDL.Opt(Coupon)],
        [],
      ),
    'adminUpdateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
    'adminUpdateProduct' : IDL.Func(
        [ProductId, UpdateProductInput],
        [IDL.Opt(Product)],
        [],
      ),
    'cancelOrder' : IDL.Func([OrderId], [IDL.Bool], []),
    'clearCart' : IDL.Func([], [IDL.Bool], []),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getMyOrders' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Order)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getMyReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getOrderDetail' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductRating' : IDL.Func(
        [ProductId],
        [ProductRatingSummary],
        ['query'],
      ),
    'getProductRatingSummary' : IDL.Func(
        [ProductId],
        [IDL.Opt(ProductId)],
        ['query'],
      ),
    'getProductReviews' : IDL.Func(
        [ProductId, IDL.Bool],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'listProducts' : IDL.Func(
        [ProductFilter, IDL.Nat, IDL.Nat],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'placeOrder' : IDL.Func([CreateOrderInput], [Order], []),
    'registerUser' : IDL.Func([RegisterInput], [User], []),
    'removeAddress' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'removeFromCart' : IDL.Func([ProductId], [IDL.Bool], []),
    'removeFromWishlist' : IDL.Func([ProductId], [IDL.Bool], []),
    'searchProducts' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'seedData' : IDL.Func([], [IDL.Text], []),
    'setDefaultAddress' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'submitReview' : IDL.Func([CreateReviewInput], [Review], []),
    'updateCartItem' : IDL.Func([ProductId, IDL.Nat], [IDL.Bool], []),
    'updateMyProfile' : IDL.Func([UpdateProfileInput], [User], []),
    'validateCoupon' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Vec(CategoryId)],
        [CouponValidation],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };