/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'street' : string,
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'fullName' : string,
  'state' : string,
  'phone' : string,
}
export type AnalyticsPeriod = { 'Day' : null } |
  { 'Week' : null } |
  { 'Year' : null } |
  { 'Month' : null };
export interface CartItem {
  'productId' : ProductId,
  'addedAt' : Timestamp,
  'quantity' : bigint,
}
export interface Category {
  'id' : CategoryId,
  'name' : string,
  'slug' : string,
  'subcategories' : Array<Subcategory>,
}
export type CategoryId = bigint;
export interface Coupon {
  'id' : CouponId,
  'discountValue' : number,
  'validFrom' : Timestamp,
  'code' : string,
  'createdAt' : Timestamp,
  'discountType' : DiscountType,
  'usageCount' : bigint,
  'validTo' : Timestamp,
  'isActive' : boolean,
  'usageLimit' : [] | [bigint],
  'applicableCategories' : Array<CategoryId>,
  'minOrderAmount' : [] | [number],
}
export type CouponId = bigint;
export interface CouponValidation {
  'discountAmount' : number,
  'message' : string,
  'isValid' : boolean,
}
export interface CreateCouponInput {
  'discountValue' : number,
  'validFrom' : Timestamp,
  'code' : string,
  'discountType' : DiscountType,
  'validTo' : Timestamp,
  'usageLimit' : [] | [bigint],
  'applicableCategories' : Array<CategoryId>,
  'minOrderAmount' : [] | [number],
}
export interface CreateOrderInput {
  'couponCode' : [] | [string],
  'paymentMethod' : PaymentMethod,
  'shippingAddress' : Address,
  'items' : Array<{ 'productId' : ProductId, 'quantity' : bigint }>,
}
export interface CreateProductInput {
  'sku' : string,
  'categoryId' : CategoryId,
  'title' : string,
  'reorderPoint' : bigint,
  'tags' : Array<string>,
  'description' : string,
  'isActive' : boolean,
  'stock' : bigint,
  'compareAtPrice' : [] | [number],
  'subcategoryId' : [] | [CategoryId],
  'price' : number,
  'images' : Array<string>,
}
export interface CreateReviewInput {
  'title' : string,
  'productId' : ProductId,
  'comment' : string,
  'rating' : bigint,
  'images' : Array<string>,
}
export interface DashboardStats {
  'totalProducts' : bigint,
  'totalOrders' : bigint,
  'pendingOrders' : bigint,
  'lowStockCount' : bigint,
  'revenueToday' : number,
  'ordersToday' : bigint,
  'totalUsers' : bigint,
  'totalRevenue' : number,
}
export type DiscountType = { 'Percent' : null } |
  { 'Fixed' : null };
export interface LowStockAlert {
  'title' : string,
  'reorderPoint' : bigint,
  'productId' : ProductId,
  'stock' : bigint,
}
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'couponCode' : [] | [string],
  'trackingNumber' : [] | [string],
  'total' : number,
  'paymentMethod' : PaymentMethod,
  'discountAmount' : number,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'notes' : [] | [string],
  'shippingAddress' : Address,
  'customerId' : UserId,
  'paymentReference' : [] | [string],
  'items' : Array<OrderItem>,
  'subtotal' : number,
}
export interface OrderFilter {
  'status' : [] | [OrderStatus],
  'paymentMethod' : [] | [PaymentMethod],
  'toDate' : [] | [Timestamp],
  'fromDate' : [] | [Timestamp],
  'customerId' : [] | [UserId],
}
export type OrderId = bigint;
export interface OrderItem {
  'title' : string,
  'productId' : ProductId,
  'imageUrl' : string,
  'quantity' : bigint,
  'price' : number,
}
export type OrderStatus = { 'Refunded' : null } |
  { 'Delivered' : null } |
  { 'Cancelled' : null } |
  { 'Processing' : null } |
  { 'Shipped' : null } |
  { 'Pending' : null };
export type PaymentMethod = { 'PayPal' : null } |
  { 'Stripe' : null } |
  { 'MtnMomo' : null };
export interface Product {
  'id' : ProductId,
  'sku' : string,
  'categoryId' : CategoryId,
  'title' : string,
  'reorderPoint' : bigint,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'description' : string,
  'isActive' : boolean,
  'updatedAt' : Timestamp,
  'stock' : bigint,
  'compareAtPrice' : [] | [number],
  'subcategoryId' : [] | [CategoryId],
  'price' : number,
  'soldCount' : bigint,
  'images' : Array<string>,
}
export interface ProductFilter {
  'categoryId' : [] | [CategoryId],
  'inStockOnly' : boolean,
  'tags' : Array<string>,
  'isActive' : [] | [boolean],
  'maxPrice' : [] | [number],
  'searchTerm' : [] | [string],
  'subcategoryId' : [] | [CategoryId],
  'minPrice' : [] | [number],
}
export type ProductId = bigint;
export interface ProductRatingSummary {
  'ratingCounts' : Array<bigint>,
  'productId' : ProductId,
  'averageRating' : number,
  'totalReviews' : bigint,
}
export interface RegisterInput { 'displayName' : string, 'email' : string }
export interface RevenueByPeriod {
  'revenue' : number,
  'period' : string,
  'orderCount' : bigint,
}
export interface Review {
  'id' : ReviewId,
  'status' : ReviewStatus,
  'title' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'comment' : string,
  'updatedAt' : Timestamp,
  'rating' : bigint,
  'images' : Array<string>,
}
export type ReviewId = bigint;
export type ReviewStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export type Role = { 'Customer' : null } |
  { 'Admin' : null };
export interface Subcategory {
  'id' : CategoryId,
  'name' : string,
  'slug' : string,
}
export type Timestamp = bigint;
export interface TopProduct {
  'title' : string,
  'revenue' : number,
  'productId' : ProductId,
  'soldCount' : bigint,
}
export interface UpdateProductInput {
  'sku' : [] | [string],
  'categoryId' : [] | [CategoryId],
  'title' : [] | [string],
  'reorderPoint' : [] | [bigint],
  'tags' : [] | [Array<string>],
  'description' : [] | [string],
  'isActive' : [] | [boolean],
  'stock' : [] | [bigint],
  'compareAtPrice' : [] | [number],
  'subcategoryId' : [] | [CategoryId],
  'price' : [] | [number],
  'images' : [] | [Array<string>],
}
export interface UpdateProfileInput {
  'displayName' : [] | [string],
  'email' : [] | [string],
  'preferences' : [] | [UserPreferences],
  'avatarUrl' : [] | [string],
}
export interface User {
  'id' : UserId,
  'displayName' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'defaultAddressIndex' : [] | [bigint],
  'isActive' : boolean,
  'email' : string,
  'preferences' : UserPreferences,
  'updatedAt' : Timestamp,
  'addresses' : Array<Address>,
  'avatarUrl' : [] | [string],
}
export type UserId = Principal;
export interface UserPreferences {
  'emailNotifications' : boolean,
  'language' : string,
  'currency' : string,
}
export interface _SERVICE {
  'addAddress' : ActorMethod<[Address], boolean>,
  'addToCart' : ActorMethod<[ProductId, bigint], boolean>,
  'addToWishlist' : ActorMethod<[ProductId], boolean>,
  'adminAdjustStock' : ActorMethod<[ProductId, bigint], boolean>,
  'adminBulkSetActive' : ActorMethod<[Array<ProductId>, boolean], bigint>,
  'adminCreateCoupon' : ActorMethod<[CreateCouponInput], Coupon>,
  'adminCreateProduct' : ActorMethod<[CreateProductInput], Product>,
  'adminDeactivateCoupon' : ActorMethod<[CouponId], boolean>,
  'adminDeactivateUser' : ActorMethod<[UserId], boolean>,
  'adminDeleteProduct' : ActorMethod<[ProductId], boolean>,
  'adminGetDashboardStats' : ActorMethod<[], DashboardStats>,
  'adminGetLowStockAlerts' : ActorMethod<[], Array<LowStockAlert>>,
  'adminGetPendingReviews' : ActorMethod<[], Array<Review>>,
  'adminGetRevenueByPeriod' : ActorMethod<
    [AnalyticsPeriod, bigint],
    Array<RevenueByPeriod>
  >,
  'adminGetTopProducts' : ActorMethod<[bigint], Array<TopProduct>>,
  'adminListCoupons' : ActorMethod<[boolean], Array<Coupon>>,
  'adminListOrders' : ActorMethod<[OrderFilter, bigint, bigint], Array<Order>>,
  'adminListUsers' : ActorMethod<[bigint, bigint], Array<User>>,
  'adminModerateReview' : ActorMethod<[ReviewId, ReviewStatus], boolean>,
  'adminSetTrackingNumber' : ActorMethod<[OrderId, string], boolean>,
  'adminSetUserRole' : ActorMethod<[UserId, Role], boolean>,
  'adminUpdateCoupon' : ActorMethod<
    [CouponId, CreateCouponInput],
    [] | [Coupon]
  >,
  'adminUpdateOrderStatus' : ActorMethod<[OrderId, OrderStatus], boolean>,
  'adminUpdateProduct' : ActorMethod<
    [ProductId, UpdateProductInput],
    [] | [Product]
  >,
  'cancelOrder' : ActorMethod<[OrderId], boolean>,
  'clearCart' : ActorMethod<[], boolean>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getMyOrders' : ActorMethod<[bigint, bigint], Array<Order>>,
  'getMyProfile' : ActorMethod<[], [] | [User]>,
  'getMyReviews' : ActorMethod<[], Array<Review>>,
  'getOrderDetail' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductRating' : ActorMethod<[ProductId], ProductRatingSummary>,
  'getProductRatingSummary' : ActorMethod<[ProductId], [] | [ProductId]>,
  'getProductReviews' : ActorMethod<[ProductId, boolean], Array<Review>>,
  'getWishlist' : ActorMethod<[], Array<ProductId>>,
  'listCategories' : ActorMethod<[], Array<Category>>,
  'listProducts' : ActorMethod<[ProductFilter, bigint, bigint], Array<Product>>,
  'placeOrder' : ActorMethod<[CreateOrderInput], Order>,
  'registerUser' : ActorMethod<[RegisterInput], User>,
  'removeAddress' : ActorMethod<[bigint], boolean>,
  'removeFromCart' : ActorMethod<[ProductId], boolean>,
  'removeFromWishlist' : ActorMethod<[ProductId], boolean>,
  'searchProducts' : ActorMethod<[string, bigint], Array<Product>>,
  'seedData' : ActorMethod<[], string>,
  'setDefaultAddress' : ActorMethod<[bigint], boolean>,
  'submitReview' : ActorMethod<[CreateReviewInput], Review>,
  'updateCartItem' : ActorMethod<[ProductId, bigint], boolean>,
  'updateMyProfile' : ActorMethod<[UpdateProfileInput], User>,
  'validateCoupon' : ActorMethod<
    [string, number, Array<CategoryId>],
    CouponValidation
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];