/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Address {
    street: string;
    country: string;
    city: string;
    postalCode: string;
    fullName: string;
    state: string;
    phone: string;
}
export interface UserPreferences {
    emailNotifications: boolean;
    language: string;
    currency: string;
}
export type Timestamp = bigint;
export interface OrderItem {
    title: string;
    productId: ProductId;
    imageUrl: string;
    quantity: bigint;
    price: number;
}
export interface ProductRatingSummary {
    ratingCounts: Array<bigint>;
    productId: ProductId;
    averageRating: number;
    totalReviews: bigint;
}
export interface UpdateProductInput {
    sku?: string;
    categoryId?: CategoryId;
    title?: string;
    reorderPoint?: bigint;
    tags?: Array<string>;
    description?: string;
    isActive?: boolean;
    stock?: bigint;
    compareAtPrice?: number;
    subcategoryId?: CategoryId;
    price?: number;
    images?: Array<string>;
}
export interface TopProduct {
    title: string;
    revenue: number;
    productId: ProductId;
    soldCount: bigint;
}
export interface Subcategory {
    id: CategoryId;
    name: string;
    slug: string;
}
export interface RegisterInput {
    displayName: string;
    email: string;
}
export interface CreateOrderInput {
    couponCode?: string;
    paymentMethod: PaymentMethod;
    shippingAddress: Address;
    items: Array<{
        productId: ProductId;
        quantity: bigint;
    }>;
}
export type ReviewId = bigint;
export interface CouponValidation {
    discountAmount: number;
    message: string;
    isValid: boolean;
}
export type CouponId = bigint;
export interface CreateReviewInput {
    title: string;
    productId: ProductId;
    comment: string;
    rating: bigint;
    images: Array<string>;
}
export interface Review {
    id: ReviewId;
    status: ReviewStatus;
    title: string;
    userId: UserId;
    createdAt: Timestamp;
    productId: ProductId;
    comment: string;
    updatedAt: Timestamp;
    rating: bigint;
    images: Array<string>;
}
export interface Category {
    id: CategoryId;
    name: string;
    slug: string;
    subcategories: Array<Subcategory>;
}
export interface RevenueByPeriod {
    revenue: number;
    period: string;
    orderCount: bigint;
}
export interface User {
    id: UserId;
    displayName: string;
    createdAt: Timestamp;
    role: Role;
    defaultAddressIndex?: bigint;
    isActive: boolean;
    email: string;
    preferences: UserPreferences;
    updatedAt: Timestamp;
    addresses: Array<Address>;
    avatarUrl?: string;
}
export interface Coupon {
    id: CouponId;
    discountValue: number;
    validFrom: Timestamp;
    code: string;
    createdAt: Timestamp;
    discountType: DiscountType;
    usageCount: bigint;
    validTo: Timestamp;
    isActive: boolean;
    usageLimit?: bigint;
    applicableCategories: Array<CategoryId>;
    minOrderAmount?: number;
}
export interface DashboardStats {
    totalProducts: bigint;
    totalOrders: bigint;
    pendingOrders: bigint;
    lowStockCount: bigint;
    revenueToday: number;
    ordersToday: bigint;
    totalUsers: bigint;
    totalRevenue: number;
}
export interface Order {
    id: OrderId;
    status: OrderStatus;
    couponCode?: string;
    trackingNumber?: string;
    total: number;
    paymentMethod: PaymentMethod;
    discountAmount: number;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    notes?: string;
    shippingAddress: Address;
    customerId: UserId;
    paymentReference?: string;
    items: Array<OrderItem>;
    subtotal: number;
}
export interface ProductFilter {
    categoryId?: CategoryId;
    inStockOnly: boolean;
    tags: Array<string>;
    isActive?: boolean;
    maxPrice?: number;
    searchTerm?: string;
    subcategoryId?: CategoryId;
    minPrice?: number;
}
export interface CreateProductInput {
    sku: string;
    categoryId: CategoryId;
    title: string;
    reorderPoint: bigint;
    tags: Array<string>;
    description: string;
    isActive: boolean;
    stock: bigint;
    compareAtPrice?: number;
    subcategoryId?: CategoryId;
    price: number;
    images: Array<string>;
}
export type UserId = Principal;
export interface UpdateProfileInput {
    displayName?: string;
    email?: string;
    preferences?: UserPreferences;
    avatarUrl?: string;
}
export interface CreateCouponInput {
    discountValue: number;
    validFrom: Timestamp;
    code: string;
    discountType: DiscountType;
    validTo: Timestamp;
    usageLimit?: bigint;
    applicableCategories: Array<CategoryId>;
    minOrderAmount?: number;
}
export interface LowStockAlert {
    title: string;
    reorderPoint: bigint;
    productId: ProductId;
    stock: bigint;
}
export type CategoryId = bigint;
export type ProductId = bigint;
export interface OrderFilter {
    status?: OrderStatus;
    paymentMethod?: PaymentMethod;
    toDate?: Timestamp;
    fromDate?: Timestamp;
    customerId?: UserId;
}
export interface CartItem {
    productId: ProductId;
    addedAt: Timestamp;
    quantity: bigint;
}
export type OrderId = bigint;
export interface Product {
    id: ProductId;
    sku: string;
    categoryId: CategoryId;
    title: string;
    reorderPoint: bigint;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    isActive: boolean;
    updatedAt: Timestamp;
    stock: bigint;
    compareAtPrice?: number;
    subcategoryId?: CategoryId;
    price: number;
    soldCount: bigint;
    images: Array<string>;
}
export enum AnalyticsPeriod {
    Day = "Day",
    Week = "Week",
    Year = "Year",
    Month = "Month"
}
export enum DiscountType {
    Percent = "Percent",
    Fixed = "Fixed"
}
export enum OrderStatus {
    Refunded = "Refunded",
    Delivered = "Delivered",
    Cancelled = "Cancelled",
    Processing = "Processing",
    Shipped = "Shipped",
    Pending = "Pending"
}
export enum PaymentMethod {
    PayPal = "PayPal",
    Stripe = "Stripe",
    MtnMomo = "MtnMomo"
}
export enum ReviewStatus {
    Approved = "Approved",
    Rejected = "Rejected",
    Pending = "Pending"
}
export enum Role {
    Customer = "Customer",
    Admin = "Admin"
}
export interface backendInterface {
    addAddress(address: Address): Promise<boolean>;
    addToCart(productId: ProductId, quantity: bigint): Promise<boolean>;
    addToWishlist(productId: ProductId): Promise<boolean>;
    adminAdjustStock(id: ProductId, delta: bigint): Promise<boolean>;
    adminBulkSetActive(ids: Array<ProductId>, isActive: boolean): Promise<bigint>;
    adminCreateCoupon(input: CreateCouponInput): Promise<Coupon>;
    adminCreateProduct(input: CreateProductInput): Promise<Product>;
    adminDeactivateCoupon(id: CouponId): Promise<boolean>;
    adminDeactivateUser(userId: UserId): Promise<boolean>;
    adminDeleteProduct(id: ProductId): Promise<boolean>;
    adminGetDashboardStats(): Promise<DashboardStats>;
    adminGetLowStockAlerts(): Promise<Array<LowStockAlert>>;
    adminGetPendingReviews(): Promise<Array<Review>>;
    adminGetRevenueByPeriod(period: AnalyticsPeriod, count: bigint): Promise<Array<RevenueByPeriod>>;
    adminGetTopProducts(limit: bigint): Promise<Array<TopProduct>>;
    adminListCoupons(activeOnly: boolean): Promise<Array<Coupon>>;
    adminListOrders(filter: OrderFilter, offset: bigint, limit: bigint): Promise<Array<Order>>;
    adminListUsers(offset: bigint, limit: bigint): Promise<Array<User>>;
    adminModerateReview(id: ReviewId, status: ReviewStatus): Promise<boolean>;
    adminSetTrackingNumber(id: OrderId, trackingNumber: string): Promise<boolean>;
    adminSetUserRole(userId: UserId, role: Role): Promise<boolean>;
    adminUpdateCoupon(id: CouponId, input: CreateCouponInput): Promise<Coupon | null>;
    adminUpdateOrderStatus(id: OrderId, status: OrderStatus): Promise<boolean>;
    adminUpdateProduct(id: ProductId, input: UpdateProductInput): Promise<Product | null>;
    cancelOrder(id: OrderId): Promise<boolean>;
    clearCart(): Promise<boolean>;
    getCart(): Promise<Array<CartItem>>;
    getMyOrders(offset: bigint, limit: bigint): Promise<Array<Order>>;
    getMyProfile(): Promise<User | null>;
    getMyReviews(): Promise<Array<Review>>;
    getOrderDetail(id: OrderId): Promise<Order | null>;
    getProduct(id: ProductId): Promise<Product | null>;
    getProductRating(productId: ProductId): Promise<ProductRatingSummary>;
    getProductRatingSummary(id: ProductId): Promise<ProductId | null>;
    getProductReviews(productId: ProductId, approvedOnly: boolean): Promise<Array<Review>>;
    getWishlist(): Promise<Array<ProductId>>;
    listCategories(): Promise<Array<Category>>;
    listProducts(filter: ProductFilter, offset: bigint, limit: bigint): Promise<Array<Product>>;
    placeOrder(input: CreateOrderInput): Promise<Order>;
    registerUser(input: RegisterInput): Promise<User>;
    removeAddress(index: bigint): Promise<boolean>;
    removeFromCart(productId: ProductId): Promise<boolean>;
    removeFromWishlist(productId: ProductId): Promise<boolean>;
    searchProducts(term: string, limit: bigint): Promise<Array<Product>>;
    seedData(): Promise<string>;
    setDefaultAddress(index: bigint): Promise<boolean>;
    submitReview(input: CreateReviewInput): Promise<Review>;
    updateCartItem(productId: ProductId, quantity: bigint): Promise<boolean>;
    updateMyProfile(input: UpdateProfileInput): Promise<User>;
    validateCoupon(code: string, orderTotal: number, categoryIds: Array<CategoryId>): Promise<CouponValidation>;
}
import type { Address as _Address, AnalyticsPeriod as _AnalyticsPeriod, CategoryId as _CategoryId, Coupon as _Coupon, CouponId as _CouponId, CreateCouponInput as _CreateCouponInput, CreateOrderInput as _CreateOrderInput, CreateProductInput as _CreateProductInput, DiscountType as _DiscountType, Order as _Order, OrderFilter as _OrderFilter, OrderId as _OrderId, OrderItem as _OrderItem, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, Product as _Product, ProductFilter as _ProductFilter, ProductId as _ProductId, Review as _Review, ReviewId as _ReviewId, ReviewStatus as _ReviewStatus, Role as _Role, Timestamp as _Timestamp, UpdateProductInput as _UpdateProductInput, UpdateProfileInput as _UpdateProfileInput, User as _User, UserId as _UserId, UserPreferences as _UserPreferences } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAddress(arg0: Address): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAddress(arg0);
            return result;
        }
    }
    async addToCart(arg0: ProductId, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1);
            return result;
        }
    }
    async addToWishlist(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWishlist(arg0);
            return result;
        }
    }
    async adminAdjustStock(arg0: ProductId, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAdjustStock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAdjustStock(arg0, arg1);
            return result;
        }
    }
    async adminBulkSetActive(arg0: Array<ProductId>, arg1: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminBulkSetActive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminBulkSetActive(arg0, arg1);
            return result;
        }
    }
    async adminCreateCoupon(arg0: CreateCouponInput): Promise<Coupon> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateCoupon(to_candid_CreateCouponInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Coupon_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateCoupon(to_candid_CreateCouponInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Coupon_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminCreateProduct(arg0: CreateProductInput): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateProduct(to_candid_CreateProductInput_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Product_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateProduct(to_candid_CreateProductInput_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Product_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeactivateCoupon(arg0: CouponId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeactivateCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeactivateCoupon(arg0);
            return result;
        }
    }
    async adminDeactivateUser(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeactivateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeactivateUser(arg0);
            return result;
        }
    }
    async adminDeleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteProduct(arg0);
            return result;
        }
    }
    async adminGetDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetDashboardStats();
            return result;
        }
    }
    async adminGetLowStockAlerts(): Promise<Array<LowStockAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetLowStockAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetLowStockAlerts();
            return result;
        }
    }
    async adminGetPendingReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetPendingReviews();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetPendingReviews();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetRevenueByPeriod(arg0: AnalyticsPeriod, arg1: bigint): Promise<Array<RevenueByPeriod>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetRevenueByPeriod(to_candid_AnalyticsPeriod_n21(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetRevenueByPeriod(to_candid_AnalyticsPeriod_n21(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async adminGetTopProducts(arg0: bigint): Promise<Array<TopProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetTopProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetTopProducts(arg0);
            return result;
        }
    }
    async adminListCoupons(arg0: boolean): Promise<Array<Coupon>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListCoupons(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListCoupons(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListOrders(arg0: OrderFilter, arg1: bigint, arg2: bigint): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListOrders(to_candid_OrderFilter_n24(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListOrders(to_candid_OrderFilter_n24(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListUsers(arg0: bigint, arg1: bigint): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListUsers(arg0, arg1);
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListUsers(arg0, arg1);
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminModerateReview(arg0: ReviewId, arg1: ReviewStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminModerateReview(arg0, to_candid_ReviewStatus_n43(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminModerateReview(arg0, to_candid_ReviewStatus_n43(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async adminSetTrackingNumber(arg0: OrderId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetTrackingNumber(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetTrackingNumber(arg0, arg1);
            return result;
        }
    }
    async adminSetUserRole(arg0: UserId, arg1: Role): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetUserRole(arg0, to_candid_Role_n45(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetUserRole(arg0, to_candid_Role_n45(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async adminUpdateCoupon(arg0: CouponId, arg1: CreateCouponInput): Promise<Coupon | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateCoupon(arg0, to_candid_CreateCouponInput_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateCoupon(arg0, to_candid_CreateCouponInput_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateOrderStatus(arg0, to_candid_OrderStatus_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateOrderStatus(arg0, to_candid_OrderStatus_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async adminUpdateProduct(arg0: ProductId, arg1: UpdateProductInput): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateProduct(arg0, to_candid_UpdateProductInput_n48(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateProduct(arg0, to_candid_UpdateProductInput_n48(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelOrder(arg0: OrderId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelOrder(arg0);
            return result;
        }
    }
    async clearCart(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async getCart(): Promise<Array<CartItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return result;
        }
    }
    async getMyOrders(arg0: bigint, arg1: bigint): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders(arg0, arg1);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders(arg0, arg1);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReviews();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReviews();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderDetail(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderDetail(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderDetail(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductRating(arg0: ProductId): Promise<ProductRatingSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductRating(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductRating(arg0);
            return result;
        }
    }
    async getProductRatingSummary(arg0: ProductId): Promise<ProductId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductRatingSummary(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductRatingSummary(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductReviews(arg0: ProductId, arg1: boolean): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductReviews(arg0, arg1);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductReviews(arg0, arg1);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWishlist(): Promise<Array<ProductId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWishlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWishlist();
            return result;
        }
    }
    async listCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCategories();
            return result;
        }
    }
    async listProducts(arg0: ProductFilter, arg1: bigint, arg2: bigint): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts(to_candid_ProductFilter_n54(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts(to_candid_ProductFilter_n54(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: CreateOrderInput): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_CreateOrderInput_n57(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Order_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_CreateOrderInput_n57(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Order_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: RegisterInput): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return from_candid_User_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return from_candid_User_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeAddress(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAddress(arg0);
            return result;
        }
    }
    async removeFromCart(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async removeFromWishlist(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWishlist(arg0);
            return result;
        }
    }
    async searchProducts(arg0: string, arg1: bigint): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(arg0, arg1);
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(arg0, arg1);
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.seedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedData();
            return result;
        }
    }
    async setDefaultAddress(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setDefaultAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDefaultAddress(arg0);
            return result;
        }
    }
    async submitReview(arg0: CreateReviewInput): Promise<Review> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0);
                return from_candid_Review_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0);
            return from_candid_Review_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCartItem(arg0: ProductId, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCartItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCartItem(arg0, arg1);
            return result;
        }
    }
    async updateMyProfile(arg0: UpdateProfileInput): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(to_candid_UpdateProfileInput_n59(this._uploadFile, this._downloadFile, arg0));
                return from_candid_User_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(to_candid_UpdateProfileInput_n59(this._uploadFile, this._downloadFile, arg0));
            return from_candid_User_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateCoupon(arg0: string, arg1: number, arg2: Array<CategoryId>): Promise<CouponValidation> {
        if (this.processError) {
            try {
                const result = await this.actor.validateCoupon(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateCoupon(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_Coupon_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Coupon): Coupon {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_DiscountType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiscountType): DiscountType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ReviewStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewStatus): ReviewStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Review_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Review {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_User_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CategoryId]): CategoryId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Coupon]): Coupon | null {
    return value.length === 0 ? null : from_candid_Coupon_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProductId]): ProductId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    sku: string;
    categoryId: _CategoryId;
    title: string;
    reorderPoint: bigint;
    createdAt: _Timestamp;
    tags: Array<string>;
    description: string;
    isActive: boolean;
    updatedAt: _Timestamp;
    stock: bigint;
    compareAtPrice: [] | [number];
    subcategoryId: [] | [_CategoryId];
    price: number;
    soldCount: bigint;
    images: Array<string>;
}): {
    id: ProductId;
    sku: string;
    categoryId: CategoryId;
    title: string;
    reorderPoint: bigint;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    isActive: boolean;
    updatedAt: Timestamp;
    stock: bigint;
    compareAtPrice?: number;
    subcategoryId?: CategoryId;
    price: number;
    soldCount: bigint;
    images: Array<string>;
} {
    return {
        id: value.id,
        sku: value.sku,
        categoryId: value.categoryId,
        title: value.title,
        reorderPoint: value.reorderPoint,
        createdAt: value.createdAt,
        tags: value.tags,
        description: value.description,
        isActive: value.isActive,
        updatedAt: value.updatedAt,
        stock: value.stock,
        compareAtPrice: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.compareAtPrice)),
        subcategoryId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.subcategoryId)),
        price: value.price,
        soldCount: value.soldCount,
        images: value.images
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReviewId;
    status: _ReviewStatus;
    title: string;
    userId: _UserId;
    createdAt: _Timestamp;
    productId: _ProductId;
    comment: string;
    updatedAt: _Timestamp;
    rating: bigint;
    images: Array<string>;
}): {
    id: ReviewId;
    status: ReviewStatus;
    title: string;
    userId: UserId;
    createdAt: Timestamp;
    productId: ProductId;
    comment: string;
    updatedAt: Timestamp;
    rating: bigint;
    images: Array<string>;
} {
    return {
        id: value.id,
        status: from_candid_ReviewStatus_n19(_uploadFile, _downloadFile, value.status),
        title: value.title,
        userId: value.userId,
        createdAt: value.createdAt,
        productId: value.productId,
        comment: value.comment,
        updatedAt: value.updatedAt,
        rating: value.rating,
        images: value.images
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    couponCode: [] | [string];
    trackingNumber: [] | [string];
    total: number;
    paymentMethod: _PaymentMethod;
    discountAmount: number;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    notes: [] | [string];
    shippingAddress: _Address;
    customerId: _UserId;
    paymentReference: [] | [string];
    items: Array<_OrderItem>;
    subtotal: number;
}): {
    id: OrderId;
    status: OrderStatus;
    couponCode?: string;
    trackingNumber?: string;
    total: number;
    paymentMethod: PaymentMethod;
    discountAmount: number;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    notes?: string;
    shippingAddress: Address;
    customerId: UserId;
    paymentReference?: string;
    items: Array<OrderItem>;
    subtotal: number;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n33(_uploadFile, _downloadFile, value.status),
        couponCode: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.couponCode)),
        trackingNumber: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.trackingNumber)),
        total: value.total,
        paymentMethod: from_candid_PaymentMethod_n36(_uploadFile, _downloadFile, value.paymentMethod),
        discountAmount: value.discountAmount,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        notes: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.notes)),
        shippingAddress: value.shippingAddress,
        customerId: value.customerId,
        paymentReference: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.paymentReference)),
        items: value.items,
        subtotal: value.subtotal
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    displayName: string;
    createdAt: _Timestamp;
    role: _Role;
    defaultAddressIndex: [] | [bigint];
    isActive: boolean;
    email: string;
    preferences: _UserPreferences;
    updatedAt: _Timestamp;
    addresses: Array<_Address>;
    avatarUrl: [] | [string];
}): {
    id: UserId;
    displayName: string;
    createdAt: Timestamp;
    role: Role;
    defaultAddressIndex?: bigint;
    isActive: boolean;
    email: string;
    preferences: UserPreferences;
    updatedAt: Timestamp;
    addresses: Array<Address>;
    avatarUrl?: string;
} {
    return {
        id: value.id,
        displayName: value.displayName,
        createdAt: value.createdAt,
        role: from_candid_Role_n41(_uploadFile, _downloadFile, value.role),
        defaultAddressIndex: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.defaultAddressIndex)),
        isActive: value.isActive,
        email: value.email,
        preferences: value.preferences,
        updatedAt: value.updatedAt,
        addresses: value.addresses,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.avatarUrl))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CouponId;
    discountValue: number;
    validFrom: _Timestamp;
    code: string;
    createdAt: _Timestamp;
    discountType: _DiscountType;
    usageCount: bigint;
    validTo: _Timestamp;
    isActive: boolean;
    usageLimit: [] | [bigint];
    applicableCategories: Array<_CategoryId>;
    minOrderAmount: [] | [number];
}): {
    id: CouponId;
    discountValue: number;
    validFrom: Timestamp;
    code: string;
    createdAt: Timestamp;
    discountType: DiscountType;
    usageCount: bigint;
    validTo: Timestamp;
    isActive: boolean;
    usageLimit?: bigint;
    applicableCategories: Array<CategoryId>;
    minOrderAmount?: number;
} {
    return {
        id: value.id,
        discountValue: value.discountValue,
        validFrom: value.validFrom,
        code: value.code,
        createdAt: value.createdAt,
        discountType: from_candid_DiscountType_n7(_uploadFile, _downloadFile, value.discountType),
        usageCount: value.usageCount,
        validTo: value.validTo,
        isActive: value.isActive,
        usageLimit: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.usageLimit)),
        applicableCategories: value.applicableCategories,
        minOrderAmount: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.minOrderAmount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
}): ReviewStatus {
    return "Approved" in value ? ReviewStatus.Approved : "Rejected" in value ? ReviewStatus.Rejected : "Pending" in value ? ReviewStatus.Pending : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Refunded: null;
} | {
    Delivered: null;
} | {
    Cancelled: null;
} | {
    Processing: null;
} | {
    Shipped: null;
} | {
    Pending: null;
}): OrderStatus {
    return "Refunded" in value ? OrderStatus.Refunded : "Delivered" in value ? OrderStatus.Delivered : "Cancelled" in value ? OrderStatus.Cancelled : "Processing" in value ? OrderStatus.Processing : "Shipped" in value ? OrderStatus.Shipped : "Pending" in value ? OrderStatus.Pending : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    PayPal: null;
} | {
    Stripe: null;
} | {
    MtnMomo: null;
}): PaymentMethod {
    return "PayPal" in value ? PaymentMethod.PayPal : "Stripe" in value ? PaymentMethod.Stripe : "MtnMomo" in value ? PaymentMethod.MtnMomo : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Customer: null;
} | {
    Admin: null;
}): Role {
    return "Customer" in value ? Role.Customer : "Admin" in value ? Role.Admin : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Percent: null;
} | {
    Fixed: null;
}): DiscountType {
    return "Percent" in value ? DiscountType.Percent : "Fixed" in value ? DiscountType.Fixed : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Array<Review> {
    return value.map((x)=>from_candid_Review_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Coupon>): Array<Coupon> {
    return value.map((x)=>from_candid_Coupon_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n13(_uploadFile, _downloadFile, x));
}
function to_candid_AnalyticsPeriod_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalyticsPeriod): _AnalyticsPeriod {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_CreateCouponInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateCouponInput): _CreateCouponInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateOrderInput_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateOrderInput): _CreateOrderInput {
    return to_candid_record_n58(_uploadFile, _downloadFile, value);
}
function to_candid_CreateProductInput_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateProductInput): _CreateProductInput {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_DiscountType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscountType): _DiscountType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_OrderFilter_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderFilter): _OrderFilter {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_ProductFilter_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductFilter): _ProductFilter {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_ReviewStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewStatus): _ReviewStatus {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProductInput_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProductInput): _UpdateProductInput {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProfileInput_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProfileInput): _UpdateProfileInput {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sku: string;
    categoryId: CategoryId;
    title: string;
    reorderPoint: bigint;
    tags: Array<string>;
    description: string;
    isActive: boolean;
    stock: bigint;
    compareAtPrice?: number;
    subcategoryId?: CategoryId;
    price: number;
    images: Array<string>;
}): {
    sku: string;
    categoryId: _CategoryId;
    title: string;
    reorderPoint: bigint;
    tags: Array<string>;
    description: string;
    isActive: boolean;
    stock: bigint;
    compareAtPrice: [] | [number];
    subcategoryId: [] | [_CategoryId];
    price: number;
    images: Array<string>;
} {
    return {
        sku: value.sku,
        categoryId: value.categoryId,
        title: value.title,
        reorderPoint: value.reorderPoint,
        tags: value.tags,
        description: value.description,
        isActive: value.isActive,
        stock: value.stock,
        compareAtPrice: value.compareAtPrice ? candid_some(value.compareAtPrice) : candid_none(),
        subcategoryId: value.subcategoryId ? candid_some(value.subcategoryId) : candid_none(),
        price: value.price,
        images: value.images
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    discountValue: number;
    validFrom: Timestamp;
    code: string;
    discountType: DiscountType;
    validTo: Timestamp;
    usageLimit?: bigint;
    applicableCategories: Array<CategoryId>;
    minOrderAmount?: number;
}): {
    discountValue: number;
    validFrom: _Timestamp;
    code: string;
    discountType: _DiscountType;
    validTo: _Timestamp;
    usageLimit: [] | [bigint];
    applicableCategories: Array<_CategoryId>;
    minOrderAmount: [] | [number];
} {
    return {
        discountValue: value.discountValue,
        validFrom: value.validFrom,
        code: value.code,
        discountType: to_candid_DiscountType_n3(_uploadFile, _downloadFile, value.discountType),
        validTo: value.validTo,
        usageLimit: value.usageLimit ? candid_some(value.usageLimit) : candid_none(),
        applicableCategories: value.applicableCategories,
        minOrderAmount: value.minOrderAmount ? candid_some(value.minOrderAmount) : candid_none()
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: OrderStatus;
    paymentMethod?: PaymentMethod;
    toDate?: Timestamp;
    fromDate?: Timestamp;
    customerId?: UserId;
}): {
    status: [] | [_OrderStatus];
    paymentMethod: [] | [_PaymentMethod];
    toDate: [] | [_Timestamp];
    fromDate: [] | [_Timestamp];
    customerId: [] | [_UserId];
} {
    return {
        status: value.status ? candid_some(to_candid_OrderStatus_n26(_uploadFile, _downloadFile, value.status)) : candid_none(),
        paymentMethod: value.paymentMethod ? candid_some(to_candid_PaymentMethod_n28(_uploadFile, _downloadFile, value.paymentMethod)) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none(),
        customerId: value.customerId ? candid_some(value.customerId) : candid_none()
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sku?: string;
    categoryId?: CategoryId;
    title?: string;
    reorderPoint?: bigint;
    tags?: Array<string>;
    description?: string;
    isActive?: boolean;
    stock?: bigint;
    compareAtPrice?: number;
    subcategoryId?: CategoryId;
    price?: number;
    images?: Array<string>;
}): {
    sku: [] | [string];
    categoryId: [] | [_CategoryId];
    title: [] | [string];
    reorderPoint: [] | [bigint];
    tags: [] | [Array<string>];
    description: [] | [string];
    isActive: [] | [boolean];
    stock: [] | [bigint];
    compareAtPrice: [] | [number];
    subcategoryId: [] | [_CategoryId];
    price: [] | [number];
    images: [] | [Array<string>];
} {
    return {
        sku: value.sku ? candid_some(value.sku) : candid_none(),
        categoryId: value.categoryId ? candid_some(value.categoryId) : candid_none(),
        title: value.title ? candid_some(value.title) : candid_none(),
        reorderPoint: value.reorderPoint ? candid_some(value.reorderPoint) : candid_none(),
        tags: value.tags ? candid_some(value.tags) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        isActive: value.isActive ? candid_some(value.isActive) : candid_none(),
        stock: value.stock ? candid_some(value.stock) : candid_none(),
        compareAtPrice: value.compareAtPrice ? candid_some(value.compareAtPrice) : candid_none(),
        subcategoryId: value.subcategoryId ? candid_some(value.subcategoryId) : candid_none(),
        price: value.price ? candid_some(value.price) : candid_none(),
        images: value.images ? candid_some(value.images) : candid_none()
    };
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categoryId?: CategoryId;
    inStockOnly: boolean;
    tags: Array<string>;
    isActive?: boolean;
    maxPrice?: number;
    searchTerm?: string;
    subcategoryId?: CategoryId;
    minPrice?: number;
}): {
    categoryId: [] | [_CategoryId];
    inStockOnly: boolean;
    tags: Array<string>;
    isActive: [] | [boolean];
    maxPrice: [] | [number];
    searchTerm: [] | [string];
    subcategoryId: [] | [_CategoryId];
    minPrice: [] | [number];
} {
    return {
        categoryId: value.categoryId ? candid_some(value.categoryId) : candid_none(),
        inStockOnly: value.inStockOnly,
        tags: value.tags,
        isActive: value.isActive ? candid_some(value.isActive) : candid_none(),
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        searchTerm: value.searchTerm ? candid_some(value.searchTerm) : candid_none(),
        subcategoryId: value.subcategoryId ? candid_some(value.subcategoryId) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none()
    };
}
function to_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    couponCode?: string;
    paymentMethod: PaymentMethod;
    shippingAddress: Address;
    items: Array<{
        productId: ProductId;
        quantity: bigint;
    }>;
}): {
    couponCode: [] | [string];
    paymentMethod: _PaymentMethod;
    shippingAddress: _Address;
    items: Array<{
        productId: _ProductId;
        quantity: bigint;
    }>;
} {
    return {
        couponCode: value.couponCode ? candid_some(value.couponCode) : candid_none(),
        paymentMethod: to_candid_PaymentMethod_n28(_uploadFile, _downloadFile, value.paymentMethod),
        shippingAddress: value.shippingAddress,
        items: value.items
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName?: string;
    email?: string;
    preferences?: UserPreferences;
    avatarUrl?: string;
}): {
    displayName: [] | [string];
    email: [] | [string];
    preferences: [] | [_UserPreferences];
    avatarUrl: [] | [string];
} {
    return {
        displayName: value.displayName ? candid_some(value.displayName) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        preferences: value.preferences ? candid_some(value.preferences) : candid_none(),
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none()
    };
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalyticsPeriod): {
    Day: null;
} | {
    Week: null;
} | {
    Year: null;
} | {
    Month: null;
} {
    return value == AnalyticsPeriod.Day ? {
        Day: null
    } : value == AnalyticsPeriod.Week ? {
        Week: null
    } : value == AnalyticsPeriod.Year ? {
        Year: null
    } : value == AnalyticsPeriod.Month ? {
        Month: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    Refunded: null;
} | {
    Delivered: null;
} | {
    Cancelled: null;
} | {
    Processing: null;
} | {
    Shipped: null;
} | {
    Pending: null;
} {
    return value == OrderStatus.Refunded ? {
        Refunded: null
    } : value == OrderStatus.Delivered ? {
        Delivered: null
    } : value == OrderStatus.Cancelled ? {
        Cancelled: null
    } : value == OrderStatus.Processing ? {
        Processing: null
    } : value == OrderStatus.Shipped ? {
        Shipped: null
    } : value == OrderStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    PayPal: null;
} | {
    Stripe: null;
} | {
    MtnMomo: null;
} {
    return value == PaymentMethod.PayPal ? {
        PayPal: null
    } : value == PaymentMethod.Stripe ? {
        Stripe: null
    } : value == PaymentMethod.MtnMomo ? {
        MtnMomo: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscountType): {
    Percent: null;
} | {
    Fixed: null;
} {
    return value == DiscountType.Percent ? {
        Percent: null
    } : value == DiscountType.Fixed ? {
        Fixed: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewStatus): {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
} {
    return value == ReviewStatus.Approved ? {
        Approved: null
    } : value == ReviewStatus.Rejected ? {
        Rejected: null
    } : value == ReviewStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    Customer: null;
} | {
    Admin: null;
} {
    return value == Role.Customer ? {
        Customer: null
    } : value == Role.Admin ? {
        Admin: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
